let default_plugins = ["Cvc4"; "External_z3"; "Redux"; "Redux_smtlib"]

let z3_common_plugin = "Z3v4dot5"

let z3_other_plugins = ["Redux_z3v4dot5"; "Z3v4dot5_smtlib"]

let register_plugins_ml =
  let plugins = 
    if Vfconfig.z3_present then z3_common_plugin :: default_plugins
    else if Vfconfig.z3v4dot5_present then z3_common_plugin :: z3_other_plugins @ default_plugins
    else default_plugins
  in
  let register_plugins = plugins |> List.map (fun p -> "let () = " ^ p ^ ".register () ") |> String.concat "in\n\t" in
  let ml_content = Printf.sprintf {|(* Generated by 'gen_register_plugins.exe', do not edit *)
open Plugin

let register () = 
  %s in 
  ()
|} register_plugins in
  let oc = open_out_bin "register_plugins.ml" in
  ml_content |> Printf.fprintf oc "%s"