(* Generated by 'gen_register_plugins.exe', do not edit *)
open Plugin

let register () = 
  let () = Z3v4dot5.register () in
	let () = Redux_z3v4dot5.register () in
	let () = Z3v4dot5_smtlib.register () in
	let () = Cvc4.register () in
	let () = External_z3.register () in
	let () = Redux.register () in
	let () = Redux_smtlib.register ()  in 
  ()
