lib: [
  "_build/install/default/lib/verifast/META"
  "_build/install/default/lib/verifast/dune-package"
  "_build/install/default/lib/verifast/opam"
]
bin: [
  "_build/install/default/bin/dlsymtool"
  "_build/install/default/bin/explorer"
  "_build/install/default/bin/java_card_applet"
  "_build/install/default/bin/main_class"
  "_build/install/default/bin/mysh"
  "_build/install/default/bin/verifast"
  "_build/install/default/bin/vfide"
  "_build/install/default/bin/vfstrip"
]
doc: [
  "_build/install/default/doc/verifast/LICENSE.md"
  "_build/install/default/doc/verifast/README.Linux.md"
  "_build/install/default/doc/verifast/README.MacOS.md"
  "_build/install/default/doc/verifast/README.Windows.md"
  "_build/install/default/doc/verifast/README.Z3v4.5.md"
  "_build/install/default/doc/verifast/README.md"
  "_build/install/default/doc/verifast/README.txt"
]
